TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Dotpulse.Visibility': true
    userInterface:
      translation:
        autoInclude:
          'Dotpulse.Visibility': ['NodeTypes/*']

Dotpulse:
  Visibility:
    includeCSS: false
