
Dotpulse:
  Visibility:
    includeCSS: false
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Dotpulse.Visibility:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Dotpulse.Visibility: true
